docs: support Valine Comment System
wangchucheng/hugo-eureka-docs pull request #4
Opened 2021-04-11 12:08 UTC by HerbertHe

2021-04-11 12:30 UTC, wangchucheng requested changes
Thanks! Please add some additional info about valine as above.

2021-04-11 12:30 UTC, wangchucheng commented on zh/customization.md
> +Eureka支持使用Disqus，Utterances，Valine和Commento作为评论系统。如需配置评论，只需对`config/_default/params.yaml`中的`comment`进行相关配置即可。
Please add the detail explanation of valine. You can refer to `comment.utterances` or `diagram.mermaid` for example.

2021-04-11 12:30 UTC, wangchucheng commented on en/customization.md
> +Eureka supports using Disqus, Utterances, Valine and Commento as comment system。If you need to configure comment, you just need to configure the `comment` in `config/_default/params.yaml`
Please add the detail explanation of valine. You can refer to `comment.utterances` or `diagram.mermaid` for example.

2021-04-11 12:57 UTC, HerbertHe reviewed
reviewed

2021-04-11 12:57 UTC, HerbertHe reviewed
viewed

2021-04-21 16:39 UTC, wangchucheng commented
Thanks for this pr. But this pr is only about adding valine support, so I can not merge other changes. And the docs have been added in e5ac2272. So I will close this PR.

If you think the document needs to be improved, please feel free to propose a new related pr. Thanks!

2021-04-21 16:39 UTC, closed without merging